
namespace GTI_v4.Classes {
    public enum TAcesso {
        CadastroPais = 1,
        CadastroPais_Alterar = 2,
        CadastroBairro = 3,
        CadastroBairro_Alterar_Fora = 4,
        CadastroBairro_Alterar_Local = 5,
        CadastroProfissao = 6,
        CadastroProfissao_Alterar = 7,
        CadastroImovel = 8,
        CadastroImovel_Alterar_Total = 9,
        CadastroImovel_Alterar_Historico = 10,
        CadastroImovel_Inativar = 11,
        CadastroFaceQuadra = 12,
        CadastroFaceQuadra_Alterar = 13,
        CadastroCidadao = 14,
        CadastroCidadao_Alterar_Total = 15,
        ExtratoContribuinte = 16,
        CadastroProcesso = 17,
        CadastroProcesso_Alterar_Basico = 18,
        CadastroProcesso_Alterar_Avancado = 19,
        CadastroProcesso_Tramitar = 20,
        CadastroProcesso_Novo = 21,
        CadastroImovel_Novo = 22,
        CadastroCondominio = 23,
        CadastroCondominio_Alterar = 24,
        CadastroImovel_IPTU = 25,
        Carta_Cobranca = 26,
        Registro_Bancario = 27,
        Atividade_Empresa = 28,
        Calculo_Imposto = 29,
        Comunicado_Isencao = 30,
        CadastroEmpresa = 31,
        CadastroEmpresa_Alterar_Total = 32,
        CadastroEmpresa_Alterar_Historico = 33,
        CadastroEmpresa_Exclusao = 34,
        Consulta_documento = 35,
        DAM_Desativar_Refis = 36,
        DAM_Imprimir = 37,
        Editar_Parcela = 38,
        Editar_Parcela_Lancamentos = 39,
        Editar_Parcela_Divida_Ativa = 40,
        DAM_Honorario = 41,
        DAM_Desconto = 42,
        Cancelamento_debito = 43

    }
}
